server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: git@github.com:willferguson/config.git
  security:
    user:
      name: admin
      password: admin

eureka:
  client:
    region: default
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/